linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

run:
  timeout: 1m
  go: '1.19'
  tests: true
  allow-parallel-runners: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-dirs:
    - vendor
    - third_party

linters-settings:
  goimports:
    local-prefixes: github.com/your-org/meal-planner