linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - goimports
    - misspell
    - unconvert

run:
  timeout: 1m
  go: '1.19'
  skip-dirs:
    - vendor
    - third_party

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/your-org/meal-planner