version: '3'

vars:
  GLEAM_DIR: '{{.ROOT_DIR}}/gleam'
  APP_DB: 'meal_planner'
  POSTGRES_USER: 'postgres'

tasks:
  # ============================================================================
  # Main Entry Point - Start Everything
  # ============================================================================
  start:
    desc: "🚀 Start the entire meal planner application (Database + API)"
    cmds:
      - task: banner
      - task: check:dependencies
      - task: db:ensure
      - task: api:start
      - task: status
      - |
        echo ""
        echo "✅ Meal Planner is ready!"
        echo ""
        echo "📱 Access points:"
        echo "   - API Server:    http://localhost:8080/health"
        echo ""

  banner:
    desc: "Show startup banner"
    cmds:
      - |
        echo "🍽️  Meal Planner - Full Stack Startup"
        echo "======================================"
        echo ""
    silent: true

  # ============================================================================
  # Dependency Checks
  # ============================================================================
  check:dependencies:
    desc: "Check required dependencies"
    cmds:
      - |
        echo "🔍 Checking dependencies..."

        # Check Gleam
        if ! command -v gleam &> /dev/null; then
          echo "❌ Gleam not found. Install from: https://gleam.run"
          exit 1
        fi
        echo "   ✓ Gleam $(gleam --version | grep -oP '\d+\.\d+\.\d+')"

        # Check PostgreSQL
        if ! command -v psql &> /dev/null; then
          echo "❌ PostgreSQL not found. Install: sudo pacman -S postgresql"
          exit 1
        fi
        echo "   ✓ PostgreSQL $(psql --version | grep -oP '\d+\.\d+')"

        # Check Docker
        if ! command -v docker &> /dev/null; then
          echo "❌ Docker not found. Install from: https://docker.com"
          exit 1
        fi
        echo "   ✓ Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

        # Check go-task
        if ! command -v task &> /dev/null; then
          echo "❌ Task not found. Install: sudo pacman -S go-task"
          exit 1
        fi
        echo "   ✓ Task $(task --version | grep -oP '\d+\.\d+\.\d+')"

        echo ""
    silent: true

  # ============================================================================
  # Database Management
  # ============================================================================
  db:ensure:
    desc: "Ensure PostgreSQL is running and databases exist"
    cmds:
      - task: db:check-running
      - task: db:create-if-missing
      - task: db:verify

  db:check-running:
    desc: "Check if PostgreSQL is running"
    cmds:
      - |
        echo "📊 Checking PostgreSQL..."
        if ! pg_isready -q; then
          echo "⚠️  PostgreSQL is not running. Starting..."
          sudo systemctl start postgresql
          sleep 2
        fi
        echo "   ✓ PostgreSQL is running"
    silent: true

  db:create-if-missing:
    desc: "Create databases if they don't exist"
    cmds:
      - |
        # Check and create meal_planner database
        if ! psql -U {{.POSTGRES_USER}} -lqt | cut -d \| -f 1 | grep -qw {{.APP_DB}}; then
          echo "   Creating {{.APP_DB}} database..."
          createdb -U {{.POSTGRES_USER}} {{.APP_DB}}
        fi
    silent: true

  db:verify:
    desc: "Verify database content"
    cmds:
      - |
        FOOD_COUNT=$(psql -U {{.POSTGRES_USER}} -d {{.APP_DB}} -tAc "SELECT COUNT(*) FROM foods" 2>/dev/null || echo "0")
        if [ "$FOOD_COUNT" -gt "0" ]; then
          echo "   ✓ Database has $FOOD_COUNT foods"
        else
          echo "   ⚠️  Database is empty. Run migrations: task db:migrate"
        fi
        echo ""
    silent: true

  db:migrate:
    desc: "Run database migrations"
    dir: '{{.GLEAM_DIR}}'
    cmds:
      - |
        echo "📊 Running migrations..."
        for migration in migrations_pg/*.sql; do
          echo "   Applying $(basename $migration)..."
          psql -U {{.POSTGRES_USER}} -d {{.APP_DB}} -f "$migration"
        done
        echo "   ✓ Migrations complete"

  db:import:
    desc: "Import USDA food database (takes ~5 minutes)"
    dir: '{{.GLEAM_DIR}}'
    deps: [build]
    cmds:
      - |
        echo "📥 Importing USDA food database..."
        echo "   This will take approximately 5 minutes..."
        gleam run -m scripts/init_pg
        echo "   ✓ Import complete"

  # ============================================================================
  # API Server
  # ============================================================================
  api:start:
    desc: "Start the Gleam API server"
    dir: '{{.GLEAM_DIR}}'
    deps: [build]
    cmds:
      - task: api:stop
      - |
        echo "🚀 Starting API server..."
        nohup gleam run > /tmp/meal-planner-api.log 2>&1 &
        echo $! > /tmp/meal-planner-api.pid

        # Wait for server to be ready
        echo "   Waiting for API server..."
        for i in {1..10}; do
          if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
            echo "   ✓ API server is ready"
            echo ""
            break
          fi
          sleep 1
        done
    silent: true

  api:stop:
    desc: "Stop the API server"
    cmds:
      - |
        if [ -f /tmp/meal-planner-api.pid ]; then
          kill $(cat /tmp/meal-planner-api.pid) 2>/dev/null || true
          rm /tmp/meal-planner-api.pid
        fi
        pkill -f "gleam run" 2>/dev/null || true
    silent: true

  api:logs:
    desc: "Show API server logs"
    cmds:
      - tail -f /tmp/meal-planner-api.log

  api:restart:
    desc: "Restart the API server"
    cmds:
      - task: api:stop
      - task: api:start

  # ============================================================================
  # Build Tasks
  # ============================================================================
  build:
    desc: "Build the Gleam application"
    dir: '{{.GLEAM_DIR}}'
    sources:
      - 'src/**/*.gleam'
      - 'gleam.toml'
    generates:
      - 'build/**/*'
    cmds:
      - gleam build

  # ============================================================================
  # Development Tasks
  # ============================================================================
  dev:
    desc: "Development mode - build and run with auto-reload"
    dir: '{{.GLEAM_DIR}}'
    cmds:
      - task: build
      - gleam run

  test:
    desc: "Run all tests"
    dir: '{{.GLEAM_DIR}}'
    cmds:
      - gleam test

  format:
    desc: "Format all Gleam code"
    dir: '{{.GLEAM_DIR}}'
    cmds:
      - gleam format

  clean:
    desc: "Clean build artifacts"
    dir: '{{.GLEAM_DIR}}'
    cmds:
      - gleam clean

  # ============================================================================
  # Status & Management
  # ============================================================================
  status:
    desc: "Show status of all services"
    cmds:
      - |
        echo "📊 Service Status"
        echo "=================="
        echo ""

        # Database
        if pg_isready -q; then
          echo "✅ PostgreSQL: Running"
        else
          echo "❌ PostgreSQL: Stopped"
        fi

        # API Server
        if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
          echo "✅ API Server: Running (http://localhost:8080)"
        else
          echo "❌ API Server: Stopped"
        fi
        echo ""

  stop:
    desc: "Stop all services"
    cmds:
      - task: api:stop
      - echo "🛑 All services stopped"

  restart:
    desc: "Restart all services"
    cmds:
      - task: stop
      - task: start

  # ============================================================================
  # Useful Commands
  # ============================================================================
  open:api:
    desc: "Open API health endpoint in browser"
    cmds:
      - xdg-open http://localhost:8080/health || open http://localhost:8080/health

  help:
    desc: "Show available tasks"
    cmds:
      - task --list
