version: '3'

vars:
  APP_DB: 'meal_planner'
  POSTGRES_USER: 'postgres'

tasks:
  # ============================================================================
  # Main Entry Point - Start Everything
  # ============================================================================
  start:
    desc: "🚀 Start the entire meal planner application (Database + API)"
    cmds:
      - task: banner
      - task: check:dependencies
      - task: db:ensure
      - task: api:start
      - task: status
      - |
        echo ""
        echo "✅ Meal Planner is ready!"
        echo ""
        echo "📱 Access points:"
        echo "   - API Server:    http://localhost:8080/health"
        echo ""

  banner:
    desc: "Show startup banner"
    cmds:
      - |
        echo "🍽️  Meal Planner - Full Stack Startup"
        echo "======================================"
        echo ""
    silent: true

  # ============================================================================
  # Dependency Checks
  # ============================================================================
  check:dependencies:
    desc: "Check required dependencies"
    cmds:
      - |
        echo "🔍 Checking dependencies..."

        # Check Gleam
        if ! command -v gleam &> /dev/null; then
          echo "❌ Gleam not found. Install from: https://gleam.run"
          exit 1
        fi
        echo "   ✓ Gleam $(gleam --version | grep -oP '\d+\.\d+\.\d+')"

        # Check PostgreSQL
        if ! command -v psql &> /dev/null; then
          echo "❌ PostgreSQL not found. Install: sudo pacman -S postgresql"
          exit 1
        fi
        echo "   ✓ PostgreSQL $(psql --version | grep -oP '\d+\.\d+')"

        # Check Docker
        if ! command -v docker &> /dev/null; then
          echo "❌ Docker not found. Install from: https://docker.com"
          exit 1
        fi
        echo "   ✓ Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

        # Check go-task
        if ! command -v task &> /dev/null; then
          echo "❌ Task not found. Install: sudo pacman -S go-task"
          exit 1
        fi
        echo "   ✓ Task $(task --version | grep -oP '\d+\.\d+\.\d+')"

        echo ""
    silent: true

  # ============================================================================
  # Database Management
  # ============================================================================
  db:ensure:
    desc: "Ensure PostgreSQL is running and databases exist"
    cmds:
      - task: db:check-running
      - task: db:create-if-missing
      - task: db:verify

  db:check-running:
    desc: "Check if PostgreSQL is running"
    cmds:
      - |
        echo "📊 Checking PostgreSQL..."
        if ! pg_isready -q; then
          echo "⚠️  PostgreSQL is not running. Starting..."
          sudo systemctl start postgresql
          sleep 2
        fi
        echo "   ✓ PostgreSQL is running"
    silent: true

  db:create-if-missing:
    desc: "Create databases if they don't exist"
    cmds:
      - |
        # Check and create meal_planner database
        if ! psql -U {{.POSTGRES_USER}} -lqt | cut -d \| -f 1 | grep -qw {{.APP_DB}}; then
          echo "   Creating {{.APP_DB}} database..."
          createdb -U {{.POSTGRES_USER}} {{.APP_DB}}
        fi
    silent: true

  db:verify:
    desc: "Verify database content"
    cmds:
      - |
        FOOD_COUNT=$(psql -U {{.POSTGRES_USER}} -d {{.APP_DB}} -tAc "SELECT COUNT(*) FROM foods" 2>/dev/null || echo "0")
        if [ "$FOOD_COUNT" -gt "0" ]; then
          echo "   ✓ Database has $FOOD_COUNT foods"
        else
          echo "   ⚠️  Database is empty. Run schema files: task db:migrate"
        fi
        echo ""
    silent: true

  db:migrate:
    desc: "Run database schema"
    cmds:
      - |
        echo "📊 Running schema..."
        for schema_file in schema/*.sql; do
          echo "   Applying $(basename $schema_file)..."
          psql -U {{.POSTGRES_USER}} -d {{.APP_DB}} -f "$schema_file"
        done
        echo "   ✓ Schema complete"

  db:import:
    desc: "Import USDA food database (takes ~5 minutes)"
    deps: [build]
    cmds:
      - |
        echo "📥 Importing USDA food database..."
        echo "   This will take approximately 5 minutes..."
        gleam run -m scripts/init_pg
        echo "   ✓ Import complete"

  # ============================================================================
  # API Server
  # ============================================================================
  api:start:
    desc: "Start the Gleam API server"
    deps: [build]
    cmds:
      - task: api:stop
      - |
        echo "🚀 Starting API server..."
        nohup gleam run > /tmp/meal-planner-api.log 2>&1 &
        echo $! > /tmp/meal-planner-api.pid

        # Wait for server to be ready
        echo "   Waiting for API server..."
        for i in {1..10}; do
          if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
            echo "   ✓ API server is ready"
            echo ""
            break
          fi
          sleep 1
        done
    silent: true

  api:stop:
    desc: "Stop the API server"
    cmds:
      - |
        if [ -f /tmp/meal-planner-api.pid ]; then
          kill $(cat /tmp/meal-planner-api.pid) 2>/dev/null || true
          rm /tmp/meal-planner-api.pid
        fi
        pkill -f "gleam run" 2>/dev/null || true
    silent: true

  api:logs:
    desc: "Show API server logs"
    cmds:
      - tail -f /tmp/meal-planner-api.log

  api:restart:
    desc: "Restart the API server"
    cmds:
      - task: api:stop
      - task: api:start

  # ============================================================================
  # Build Tasks
  # ============================================================================
  build:
    desc: "Build the Gleam application"
    sources:
      - 'src/**/*.gleam'
      - 'gleam.toml'
    generates:
      - 'build/**/*'
    cmds:
      - gleam build

  build:rust:
    desc: "Build Rust binaries to bin/"
    sources:
      - 'src/**/*.rs'
      - 'Cargo.toml'
    generates:
      - 'bin/*'
    cmds:
      - cargo build --release
      - mkdir -p bin
      - cp target/release/tandoor_* bin/ 2>/dev/null || true
      - cp target/release/fatsecret_* bin/ 2>/dev/null || true
      - echo "✓ Binaries built to bin/"

  build:all:
    desc: "Build everything"
    cmds:
      - task: build
      - task: build:rust

  # ============================================================================
  # Development Tasks
  # ============================================================================
  dev:
    desc: "Development mode - build and run with auto-reload"
    cmds:
      - task: build
      - gleam run

  test:
    desc: "Run all tests"
    cmds:
      - gleam test

  format:
    desc: "Format all Gleam code"
    cmds:
      - gleam format

  clean:
    desc: "Clean build artifacts"
    cmds:
      - gleam clean

  # ============================================================================
  # Tandoor Recipe Manager
  # ============================================================================
  tandoor:start:
    desc: "🍳 Start Tandoor recipe manager"
    cmds:
      - |
        echo "🍳 Starting Tandoor..."

        # Check if already running
        if docker ps --format '{{.Names}}' | grep -q '^tandoor$'; then
          echo "   ✓ Tandoor is already running"
          exit 0
        fi

        # Check if container exists but stopped
        if docker ps -a --format '{{.Names}}' | grep -q '^tandoor$'; then
          echo "   Restarting existing container..."
          docker start tandoor
        else
          echo "   Creating new Tandoor container..."
          docker run -d \
            --name tandoor \
            -p 8000:80 \
            -e SECRET_KEY="dev-secret-key-not-for-production-use-123456789" \
            -e ALLOWED_HOSTS="*" \
            -e CSRF_TRUSTED_ORIGINS="http://localhost:8000" \
            -v tandoor_staticfiles:/opt/recipes/staticfiles \
            -v tandoor_mediafiles:/opt/recipes/mediafiles \
            -v tandoor_db:/opt/recipes/database \
            vabene1111/recipes:latest
        fi

        # Wait for Tandoor to be ready
        echo "   Waiting for Tandoor to start..."
        for i in {1..30}; do
          if curl -sf http://localhost:8000 > /dev/null 2>&1; then
            echo "   ✓ Tandoor is ready at http://localhost:8000"
            echo ""
            echo "   📝 First time setup:"
            echo "      1. Visit http://localhost:8000"
            echo "      2. Create admin account"
            echo "      3. Go to Settings > API > Create Token"
            echo "      4. Set TANDOOR_API_TOKEN in your .env"
            break
          fi
          sleep 2
        done
    silent: true

  tandoor:stop:
    desc: "Stop Tandoor"
    cmds:
      - docker stop tandoor 2>/dev/null || true
      - echo "   ✓ Tandoor stopped"
    silent: true

  tandoor:logs:
    desc: "Show Tandoor logs"
    cmds:
      - docker logs -f tandoor

  tandoor:shell:
    desc: "Open shell in Tandoor container"
    cmds:
      - docker exec -it tandoor /bin/bash

  tandoor:db:create:
    desc: "Create Tandoor database"
    cmds:
      - |
        if ! psql -U {{.POSTGRES_USER}} -lqt | cut -d \| -f 1 | grep -qw tandoor; then
          echo "   Creating tandoor database..."
          createdb -U {{.POSTGRES_USER}} tandoor
          echo "   ✓ Database created"
        else
          echo "   ✓ Tandoor database exists"
        fi
    silent: true

  # ============================================================================
  # Status & Management
  # ============================================================================
  status:
    desc: "Show status of all services"
    cmds:
      - |
        echo "📊 Service Status"
        echo "=================="
        echo ""

        # Database
        if pg_isready -q; then
          echo "✅ PostgreSQL: Running"
        else
          echo "❌ PostgreSQL: Stopped"
        fi

        # API Server
        if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
          echo "✅ API Server: Running (http://localhost:8080)"
        else
          echo "❌ API Server: Stopped"
        fi

        # Tandoor
        if docker ps --format '{{.Names}}' | grep -q '^tandoor$'; then
          echo "✅ Tandoor: Running (http://localhost:8000)"
        else
          echo "❌ Tandoor: Stopped (run: task tandoor:start)"
        fi
        echo ""

  stop:
    desc: "Stop all services"
    cmds:
      - task: api:stop
      - task: tandoor:stop
      - echo "🛑 All services stopped"

  restart:
    desc: "Restart all services"
    cmds:
      - task: stop
      - task: start

  # ============================================================================
  # Useful Commands
  # ============================================================================
  open:api:
    desc: "Open API health endpoint in browser"
    cmds:
      - xdg-open http://localhost:8080/health || open http://localhost:8080/health

  help:
    desc: "Show available tasks"
    cmds:
      - task --list
