#!/usr/bin/env bash
# Install performance tracking git hooks
# This script sets up post-commit hook to track test performance every 5 commits

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
POST_COMMIT_HOOK="$HOOKS_DIR/post-commit"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

# Check if we're in a git repository
if [[ ! -d "$PROJECT_ROOT/.git" ]]; then
    log_error "Not in a git repository"
    exit 1
fi

# Create hooks directory if it doesn't exist
mkdir -p "$HOOKS_DIR"

# Check if post-commit hook already exists
if [[ -f "$POST_COMMIT_HOOK" ]]; then
    log_warning "post-commit hook already exists"
    log_info "Checking if performance tracking is already configured..."

    if grep -q "perf-track.sh" "$POST_COMMIT_HOOK"; then
        log_info "Performance tracking already configured in post-commit hook"
        exit 0
    else
        log_warning "Appending performance tracking to existing post-commit hook"
        # Append to existing hook
        cat >> "$POST_COMMIT_HOOK" <<'EOF'

# Performance tracking (every 5 commits)
# Added by scripts/install-perf-hooks.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
if [[ -x "$SCRIPT_DIR/scripts/perf-track.sh" ]]; then
    "$SCRIPT_DIR/scripts/perf-track.sh" || true
fi
EOF
        log_success "Performance tracking appended to post-commit hook"
    fi
else
    log_info "Creating new post-commit hook with performance tracking..."

    cat > "$POST_COMMIT_HOOK" <<'EOF'
#!/usr/bin/env bash
# Git post-commit hook - Performance Tracking
# Automatically tracks test execution performance every 5 commits
# Generated by scripts/install-perf-hooks.sh

set -e

# Get project root (2 levels up from .git/hooks)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"

# Run performance tracking script
if [[ -x "$PROJECT_ROOT/scripts/perf-track.sh" ]]; then
    echo ""
    echo "Performance Tracking (post-commit hook)"
    "$PROJECT_ROOT/scripts/perf-track.sh" || true
    echo ""
fi
EOF

    chmod +x "$POST_COMMIT_HOOK"
    log_success "Created post-commit hook with performance tracking"
fi

echo ""
log_success "Performance tracking git hooks installed successfully!"
echo ""
echo "Features:"
echo "  • Automatic tracking every 5 commits"
echo "  • Test execution time measurement"
echo "  • Regression detection (20% warning, 50% critical)"
echo "  • Historical data in .perf-tracking/test-execution.csv"
echo ""
echo "Manual Commands:"
echo "  • Force tracking:   ./scripts/perf-track.sh --force"
echo "  • View analysis:    ./scripts/perf-analyze.sh"
echo "  • Generate report:  ./scripts/perf-analyze.sh --report"
echo ""
